--Add conditional items here
layers.AddChargedItem("Warp Cudgel")
layers.AddChargedItem("Trick Staff II")
layers.AddChargedItem("Treat Staff II")
layers.AddChargedItem("Tavnazian Ring")
layers.AddChargedItem("Dem Ring")
layers.AddChargedItem("Mea Ring")
layers.AddChargedItem("Holla Ring")
layers.AddChargedItem("Altep Ring")
layers.AddChargedItem("Vahzl Ring")
layers.AddChargedItem("Yhoat Ring")
layers.AddChargedItem("Powder Boots")
layers.AddChargedItem("Reraise Gorget")
layers.AddChargedItem("Reraise Earring")
layers.AddChargedItem("Reraise Hairpin")
layers.AddChargedItem("Dcl.Grd. Ring")
layers.AddChargedItem("Empress Band")
layers.AddChargedItem("Emperor Band")
layers.AddChargedItem("Chariot Band")
layers.AddChargedItem("Anniversary Ring")
layers.AddChargedItem("Return Ring")
layers.AddChargedItem("Homing Ring")
layers.AddChargedItem("Blink Band")
layers.AddChargedItem("Reraise Gorget")
layers.AddChargedItem("Mandra. Suit")
--HXI Anni#2 12/24/24
layers.AddChargedItem("Republic Earring")
layers.AddChargedItem("Kingdom Earring")
layers.AddChargedItem("Federation Earring")
--Purgonorgo Teleport items
layers.AddChargedItem("Custom Gilet +1")
layers.AddChargedItem("Custom Top +1")
layers.AddChargedItem("Magna Gilet +1")
layers.AddChargedItem("Magna Top +1")
layers.AddChargedItem("Savage Top +1")
layers.AddChargedItem("Elder Gilet +1")
layers.AddChargedItem("Wonder Maillot +1")
layers.AddChargedItem("Wonder Top +1")

--Add enchanted items here
layers.AddEnchantedItem("Breath Mantle")
layers.AddEnchantedItem("High Brth. Mantle")
layers.AddEnchantedItem("Stoneskin Torque")
